export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const REMOVE_POST = 'REMOVE_POST';


export const API_BASE_URL = process.env.REACT_APP_BASE_URL_API;
